### PR TITLE
Nathaliek/core 5400/add table cleanup delay test

### PR DESCRIPTION
**Pull request by NathalieKaligirwa**
@urmilan 
This branch has the most up to date changes. The name of the branch is misleading (I was experimenting with a new gui thus the 'test' part). 
Changes in soql-postgres-adapter: 

- make sure all functions involved in dataset deletion in postgres-adapter are up to date.

### CODE REVIEW

**Comment by NathalieKaligirwa** [comment]
Jenkins is failing because the version of dc is not available yet. On release, add the correct dc dependency.

**Comment by urmilan** [comment]
I have the same feedback here as for the data-coordinator pull request. We should update `SqlDatasetDropper` to delete both t-tables and metadata, and then remove all table dropper thread code in the secondary.

**Comment by urmilan** [comment]
Reviewed up to f1c4587

**Comment by urmilan** [comment]
I _think_ once we remove the `tableCleanupDelay` config in coordinator-lib, the only change needed in this repo will be the dependency bump?

**Pull request closed without merging**
