### PR TITLE
Implement distance_in_meters function

### PR DESCRIPTION
**Pull request by urmilan**

### CODE REVIEW

**Comment by chrismetcalf** [comment]
@urmilan Can this be used in `$order` and `$select` as well?

**Comment by znep** [comment]
@urmilan I merged the soql-reference change so you can go ahead and release that and update this pr to depend on it...

**Comment by urmilan** [comment]
Thanks @znep, see a70a7f1

**Comment by chrismetcalf** [comment]
Yay! :fireworks:

**Pull request merged**
