### PR TITLE
Add data shape version

### PR DESCRIPTION
**Pull request by rjmac**
This doesn't actually care about it, but because it uses DC's database
code it needs to fake caring.

### CODE REVIEW

**Comment by chitang** [comment]
I thought we are going to actually make use of data_shape_version for rollup names to significantly improve rollup write efficiency.

**Review by sjzavaleta — APPROVED** [review]

**Comment by rjmac** [comment]
I didn't think that; that was what I did the batching stuff for.

**Comment by rjmac** [comment]
(we can always add DSV to secondaries if we decide that we do need it, but it requires a change to the secondary API)

**Comment by chitang** [comment]
For example, a dataset is published, has 69 rollups and fully replicated.  Then, add one more rollup.  Currently, it will have to rewrite all 69 + 1 rollups.  I think we can do much better and just refresh one rollup.

**Pull request merged**
