### PR TITLE
EN-60862: for staging push to internal registry only

### PR DESCRIPTION
**Pull request by sarah-salinas**
## Before

After building docker images, they are pushed to all registries.

## After

After building docker images:
- if the image is for staging, it is pushed only to the internal registry
- if the image is for release, it is pushed to all registries

### CODE REVIEW

**Comment by sarah-salinas** [comment]
## Testing

- PR check ✅ 
- Simulated main:  https://jenkins-build.socrata.com/job/soql-postgres-adapter-branch/1/consoleFull - only pushed to internal registry for soql-server-pg and secondary-watcher-pg, deploy to staging succeeded ✅ 
- Release Dry Run: https://jenkins-build.socrata.com/job/soql-postgres-adapter-branch/2/consoleFull - pushed to all registries ✅

**Comment by sarah-salinas** [comment]
## Retesting after changes

- PR check ✅
- Simulated main: https://jenkins-build.socrata.com/job/soql-postgres-adapter-branch/3/consoleFull - only pushed to internal registry for soql-server-pg and secondary-watcher-pg, deploy to staging succeeded ✅
- Release Dry Run: https://jenkins-build.socrata.com/job/soql-postgres-adapter-branch/4/consoleFull - pushed to all registries ✅

Note, for the simulated main build, the final stage "Deploy Citus Mirrors" failed -- this matches the main branch in staging. The stage has been failing in staging since July 6th: https://jenkins-build.socrata.com/job/data-platform/job/soql-server/job/Soql-server-pg%20Build%20Pipeline/job/main/ When I let Zach know he said this was expected for now.

**Review by saraid — APPROVED** [review]
Gonna assume the Docker tag itself isn't changing.

**Comment by sarah-salinas** [comment]
Correct, DOCKER_TAG itself is not changing at this time.
I just recently merged https://github.com/socrata/pipelines/pull/119 which returns DOCKER_TAG from the docker_build function.

**Comment by sarah-salinas** [comment]
## Retesting

- PR ✅ 
- https://jenkins-build.socrata.com/job/soql-postgres-adapter-branch/5/console ✅ 
- https://jenkins-build.socrata.com/job/soql-postgres-adapter-branch/6/console ✅

**Pull request merged**
